version: '3.9'
services:
  frontend:
    build: # Node.js
      context: . 
      dockerfile: Dockerfile  
    working_dir: /app
    volumes:
       - ./mil-library/:/app
       - node_modules:/app/node_modules
    tty: true
    ports:
      - '5173:5173'
    command: yarn dev --host
volumes:
  node_modules:
